mylist = []
print(f"Empty list:\n{mylist}")
mylist1 = [1,5,10]
print(f"Created new list:\n{mylist1}")
mylist1.append(45)
print(f"Appended 45 into mylist1:\n{mylist1}") 
mylist1.extend(["Smit",5.4])
print(f"Extended lisy by ['Smit',5.4]\n{mylist1}")
mylist1.insert(2,50)
print(f"inserted 50 at 2nd position:\n{mylist1}")
mylist1.pop()
print(f"pop last element from mylist1:\n{mylist1}")
mylist1.remove(50)
print(f"removed 50 from the list:\n{mylist1}")
mylist1.pop(2)
print(f"pop element of 2nd position from mylist1:\n{mylist1}")
mylist1.reverse()
print(f"reversed the list:\n{mylist1}")
x = mylist1.count(5)
print(f"counted the elements of the list:\n{x}")
y = mylist1.index(5)
print(f"Return the indext of 5: {y}")
print(f"accessed element at index 2: {mylist1[2]}")
print(f"accessed elements from 0 to 2: {mylist1[0:3]}")
print(f"Reverse the list: {mylist1[::-1]}")
mylist1.clear()
print(f"cleared the list: {mylist1}")
